version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: start-dev
    ports:
      - 8081:8080
    depends_on:
      - postgres
    volumes:
      - ./setup-keycloak.sh:/opt/keycloak/setup-keycloak.sh
    entrypoint: |
        /bin/sh -c "
          /opt/keycloak/bin/kc.sh start-dev & 
          sleep 20 &&
          /opt/keycloak/setup-keycloak.sh && 
          tail -f /dev/null
        "
    restart: unless-stopped


  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloakdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local
